[relaychain]
default_command = "polkadot"
chain = "westend-local"
# chain-spec-builder create -t development --runtime ../polkadot-sdk/target/release/wbuild/westend-runtime/westend_runtime.compact.compressed.wasm named-preset local_testnet
chain_spec_path = "./rc.json"

[[relaychain.nodes]]
name = "alice"
validator = true
rpc_port = 9944
args = ["--no-hardware-benchmarks"]

[[relaychain.nodes]]
name = "bob"
validator = true
rpc_port = 9945
args = ["--no-hardware-benchmarks"]

[[parachains]]
id = 1000
cumulus_based = true
# chain-spec-builder create -t development --relay-chain westend --para-id 1000 --runtime ../polkadot-sdk/target/release/wbuild/asset-hub-westend-runtime/asset_hub_westend_runtime.compact.compressed.wasm named-preset development
chain_spec_path = "./ah.json"

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
command = "polkadot-omni-node"
args = ["--force-authoring", "--no-hardware-benchmarks"]
rpc_port = 9946
